// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22PfZNssmNwQ-8G0Q3X9cIIY0UMVuAT8',
    appId: '1:577783720197:web:5f942bfd50211c50f72f6c',
    messagingSenderId: '577783720197',
    projectId: 'sanki-fb-auth-bloc',
    authDomain: 'sanki-fb-auth-bloc.firebaseapp.com',
    storageBucket: 'sanki-fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmmxCDQftdrcsjCn2xMfmkDIlFBfDeW0',
    appId: '1:577783720197:android:28eb3e428bf7c1b7f72f6c',
    messagingSenderId: '577783720197',
    projectId: 'sanki-fb-auth-bloc',
    storageBucket: 'sanki-fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MI4AXGEGebWqPseS2CeWf10R69oiCKk',
    appId: '1:577783720197:ios:0b4f042a6f23ac11f72f6c',
    messagingSenderId: '577783720197',
    projectId: 'sanki-fb-auth-bloc',
    storageBucket: 'sanki-fb-auth-bloc.appspot.com',
    iosClientId: '577783720197-or4fmelhgdccl04p2ndk7di92vp5c7eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthBloc',
  );
}
